[project]
name = "cli-surf-report"
version = "0.1.2"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "click>=8.5.0",
    "openmeteo-requests>=1.7.5",
    "rich>=13.0.0",
]
[project.scripts]
surf = "main:surf"

[tool.setuptools]
py-modules = [
    "api_request",
    "callbacks",
    "config",
    "database_functions",
    "enums",
    "main",
    "quality_calcs",
    "query_helpers",
    "report_class",
    "rich_functions",
    "surf_spot_class",
]
packages = ["data"]

[tool.setuptools.package-data]
data = ["*.csv"]

[build-system]
requires = ["setuptools>=68"]
build-backend = "setuptools.build_meta"